version: '2'

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - nilerr
    - nilnesserr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - wastedassign
  exclusions:
    generated: strict
  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true
    govet:
      enable:
        - appends
        - asmdecl
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - deepequalerrors
        - defers
        - directive
        - errorsas
        - framepointer
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - sigchanyzer
        - slog
        - stdmethods
        - stringintconv
        - structtag
        - tests
        - timeformat
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
