// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hooks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createHook = `-- name: CreateHook :one
INSERT INTO hooks (token, name)
VALUES (?, ?)
RETURNING id, token, name, created_at, updated_at
`

type CreateHookParams struct {
	Token string         `json:"token"`
	Name  sql.NullString `json:"name"`
}

func (q *Queries) CreateHook(ctx context.Context, arg CreateHookParams) (Hook, error) {
	row := q.db.QueryRowContext(ctx, createHook, arg.Token, arg.Name)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookRequest = `-- name: CreateWebhookRequest :one
INSERT INTO webhook_requests (
    hook_id,
    method,
    path,
    query,
    headers,
    body,
    remote_addr,
    content_type,
    body_size
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, hook_id, method, path, query, headers, body, remote_addr, content_type, body_size, received_at
`

type CreateWebhookRequestParams struct {
	HookID      int64          `json:"hook_id"`
	Method      string         `json:"method"`
	Path        string         `json:"path"`
	Query       string         `json:"query"`
	Headers     string         `json:"headers"`
	Body        []byte         `json:"body"`
	RemoteAddr  sql.NullString `json:"remote_addr"`
	ContentType sql.NullString `json:"content_type"`
	BodySize    int64          `json:"body_size"`
}

func (q *Queries) CreateWebhookRequest(ctx context.Context, arg CreateWebhookRequestParams) (WebhookRequest, error) {
	row := q.db.QueryRowContext(ctx, createWebhookRequest,
		arg.HookID,
		arg.Method,
		arg.Path,
		arg.Query,
		arg.Headers,
		arg.Body,
		arg.RemoteAddr,
		arg.ContentType,
		arg.BodySize,
	)
	var i WebhookRequest
	err := row.Scan(
		&i.ID,
		&i.HookID,
		&i.Method,
		&i.Path,
		&i.Query,
		&i.Headers,
		&i.Body,
		&i.RemoteAddr,
		&i.ContentType,
		&i.BodySize,
		&i.ReceivedAt,
	)
	return i, err
}

const deleteWebhookRequestsOlderThan = `-- name: DeleteWebhookRequestsOlderThan :execresult
DELETE FROM webhook_requests
WHERE received_at < datetime('now', ?)
`

func (q *Queries) DeleteWebhookRequestsOlderThan(ctx context.Context, datetime interface{}) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteWebhookRequestsOlderThan, datetime)
}

const getCountRequests = `-- name: GetCountRequests :one
SELECT COUNT(*)
FROM webhook_requests
`

func (q *Queries) GetCountRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCountRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHookByToken = `-- name: GetHookByToken :one
SELECT id, token, name, created_at, updated_at
FROM hooks
WHERE token = ?
`

func (q *Queries) GetHookByToken(ctx context.Context, token string) (Hook, error) {
	row := q.db.QueryRowContext(ctx, getHookByToken, token)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHookResponseByHookID = `-- name: GetHookResponseByHookID :one
SELECT id, hook_id, status_code, headers, body, created_at, updated_at
FROM hook_responses
WHERE hook_id = ?
`

func (q *Queries) GetHookResponseByHookID(ctx context.Context, hookID int64) (HookResponse, error) {
	row := q.db.QueryRowContext(ctx, getHookResponseByHookID, hookID)
	var i HookResponse
	err := row.Scan(
		&i.ID,
		&i.HookID,
		&i.StatusCode,
		&i.Headers,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHooks = `-- name: ListHooks :many
SELECT id, token, name, created_at, updated_at
FROM hooks
ORDER BY created_at DESC`

func (q *Queries) ListHooks(ctx context.Context) ([]Hook, error) {
	rows, err := q.db.QueryContext(ctx, listHooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hook
	for rows.Next() {
		var i Hook
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWebhookRequestsByHookID = `-- name: CountWebhookRequestsByHookID :one
SELECT COUNT(*)
FROM webhook_requests
WHERE hook_id = ?
`

func (q *Queries) CountWebhookRequestsByHookID(ctx context.Context, hookID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebhookRequestsByHookID, hookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listWebhookRequestsByHookID = `-- name: ListWebhookRequestsByHookID :many
SELECT id, hook_id, method, path, query, headers, body, remote_addr, content_type, body_size, received_at
FROM webhook_requests
WHERE hook_id = ?
ORDER BY received_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListWebhookRequestsByHookIDParams struct {
	HookID int64 `json:"hook_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWebhookRequestsByHookID(ctx context.Context, arg ListWebhookRequestsByHookIDParams) ([]WebhookRequest, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookRequestsByHookID, arg.HookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookRequest
	for rows.Next() {
		var i WebhookRequest
		if err := rows.Scan(
			&i.ID,
			&i.HookID,
			&i.Method,
			&i.Path,
			&i.Query,
			&i.Headers,
			&i.Body,
			&i.RemoteAddr,
			&i.ContentType,
			&i.BodySize,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookRequestsByTime = `-- name: ListWebhookRequestsByTime :many
SELECT
    wr.id,
    wr.hook_id,
    h.token,
    h.name,
    wr.method,
    wr.path,
    wr.query,
    wr.headers,
    wr.remote_addr,
    wr.content_type,
    wr.body_size,
    wr.received_at
FROM webhook_requests wr
JOIN hooks h ON h.id = wr.hook_id
WHERE wr.received_at <= datetime('now', ?)
ORDER BY wr.received_at DESC
`

type ListWebhookRequestsByTimeRow struct {
	ID          int64          `json:"id"`
	HookID      int64          `json:"hook_id"`
	Token       string         `json:"token"`
	Name        sql.NullString `json:"name"`
	Method      string         `json:"method"`
	Path        string         `json:"path"`
	Query       string         `json:"query"`
	Headers     string         `json:"headers"`
	RemoteAddr  sql.NullString `json:"remote_addr"`
	ContentType sql.NullString `json:"content_type"`
	BodySize    int64          `json:"body_size"`
	ReceivedAt  time.Time      `json:"received_at"`
}

func (q *Queries) ListWebhookRequestsByTime(ctx context.Context, datetime interface{}) ([]ListWebhookRequestsByTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookRequestsByTime, datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookRequestsByTimeRow
	for rows.Next() {
		var i ListWebhookRequestsByTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.HookID,
			&i.Token,
			&i.Name,
			&i.Method,
			&i.Path,
			&i.Query,
			&i.Headers,
			&i.RemoteAddr,
			&i.ContentType,
			&i.BodySize,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHookResponse = `-- name: UpsertHookResponse :one
INSERT INTO hook_responses (hook_id, status_code, headers, body)
VALUES (?, ?, ?, ?)
ON CONFLICT (hook_id) DO UPDATE SET
    status_code = excluded.status_code,
    headers = excluded.headers,
    body = excluded.body,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, hook_id, status_code, headers, body, created_at, updated_at
`

type UpsertHookResponseParams struct {
	HookID     int64  `json:"hook_id"`
	StatusCode int64  `json:"status_code"`
	Headers    string `json:"headers"`
	Body       []byte `json:"body"`
}

func (q *Queries) UpsertHookResponse(ctx context.Context, arg UpsertHookResponseParams) (HookResponse, error) {
	row := q.db.QueryRowContext(ctx, upsertHookResponse,
		arg.HookID,
		arg.StatusCode,
		arg.Headers,
		arg.Body,
	)
	var i HookResponse
	err := row.Scan(
		&i.ID,
		&i.HookID,
		&i.StatusCode,
		&i.Headers,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
