// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Hook struct {
	ID        int64          `json:"id"`
	Token     string         `json:"token"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type HookResponse struct {
	ID         int64     `json:"id"`
	HookID     int64     `json:"hook_id"`
	StatusCode int64     `json:"status_code"`
	Headers    string    `json:"headers"`
	Body       []byte    `json:"body"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type WebhookRequest struct {
	ID          int64          `json:"id"`
	HookID      int64          `json:"hook_id"`
	Method      string         `json:"method"`
	Path        string         `json:"path"`
	Query       string         `json:"query"`
	Headers     string         `json:"headers"`
	Body        []byte         `json:"body"`
	RemoteAddr  sql.NullString `json:"remote_addr"`
	ContentType sql.NullString `json:"content_type"`
	BodySize    int64          `json:"body_size"`
	ReceivedAt  time.Time      `json:"received_at"`
}
